[build]
  Command = "npm run build"
  Functions = "lambda"
  Publish = "public"
  environment = { NODE_VERSION = "14.15.0" }

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''
